databases:
  - name: spotifly
    databaseName: spotifly
    user: spotifly

services:
  - type: web
    name: spotifly
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spotifly
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: worker
    name: spotify_poller
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rake poll_spotify
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spotifly
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false